version: '3'
services: 

  etlformat1:
    build:
      dockerfile: Dockerfile
      context: ./ETL
    env_file:
      - postgres_conn.env    
    environment:
      - source_schema=datravexample
      - years=2009
      #- years=2009,2010
      - target_schema=FDZ_format1_2009
      - DATA_FOLDER_OMOP1=/ETL/Format1toOMOP
      - logname=/ETL/Format1toOMOP/ETL.log
    command: sh -c "python /ETL/Format1toOMOP/create_OMOPCDM54.py && python /ETL/Format1toOMOP/ETL_data_to_OMOP.py "
    volumes:
     - ./voc:/voc
     - ./ETL/Format1toOMOP:/ETL/Format1toOMOP
     - ./ETL/helper_func.py:/ETL/helper_func.py

  etlformat3:
    image: etlformat1:latest
    build:
      dockerfile: Dockerfile

      context: ./ETL
    env_file:
      - postgres_conn.env    
    environment:
      - target_schema=FDZ_format3_2019
      - years=2019
      - DATA_FOLDER_OMOP3=/ETL/Format3toOMOP
      - logname=/ETL/Format3toOMOP/ETL.log      
    command: sh -c "python /ETL/Format3toOMOP/create_OMOPCDM54.py && python /ETL/Format3toOMOP/ETL_data_to_OMOP.py "
    volumes:
     - ./voc:/voc
     - ./ETL/Format3toOMOP:/ETL/Format3toOMOP
     - ./ETL/helper_func.py:/ETL/helper_func.py